tbp: MACRO
    dbw BANK(\1), \1
    ENDM
IF CHALLENGE_MODE
; this set of music will play if CHALLENGE_MODE in constants.asm is set to 1, otherwise it'll play another set of music
    tbp Music_Nothing
    tbp Music_PalletTown
    tbp Music_Pokecenter
    tbp Music_Gym
    tbp Music_Pinballredfield
    tbp Music_Cities2
    tbp Music_CeladonCity
    tbp Music_CinnabarRemix
    tbp Music_VermilionCity
    tbp Music_Lavender
    tbp Music_SSAnne
    tbp Music_ProfOak
    tbp Music_MeetRival
    tbp Music_Shop
    tbp Music_Evolution
    tbp Music_PkmnHealed
    tbp Music_Route1
    tbp Music_NuggetBridge
    tbp Music_Route3
    tbp Music_Route12
    tbp Music_RBYIndigoPlateau
    tbp Music_KantoGymBattle
    tbp Music_KantoTrainerBattle
    tbp Music_KantoWildBattle
    tbp Music_FinalBattle
    tbp Music_TrainerVictory
    tbp Music_DefeatedWildMon
    tbp Music_GymLeaderVictory
    tbp Music_RBYTitleScreen
    tbp Music_RBYCredits
    tbp Music_RBYHallOfFame
    tbp Music_ProfOaksPokemonTalk
    tbp Music_BikeRiding
    tbp Music_Surfing
    tbp Music_GameCorner
    tbp Music_IntroBattle
    tbp Music_Dungeon1
    tbp Music_Dungeon2
    tbp Music_Dungeon3
    tbp Music_CinnabarMansion
    tbp Music_PokemonTower
    tbp Music_SilphCo
    tbp Music_LookHiker
    tbp Music_LookLass
    tbp Music_LookOfficer
    tbp Music_RocketBattle
    tbp Music_ChampionBattle
    tbp Music_DarkCave
    tbp Music_BattleTowerTheme
    tbp Music_VictoryRoad
    tbp Music_CeruleanGSC
    tbp Music_ViridianCity
    tbp Music_TCG2GROverworld
    tbp Music_TCG2GameCorner
    tbp Music_FrontierBrain
    tbp Music_TCG2GRCastle
    tbp Music_TCG2GRDuelTheme2
    tbp Music_JigglypuffSong
    tbp Music_MuseumGuy
    tbp Music_TCGClub2
    tbp Music_JohtoTrainerBattle
    tbp Music_LookPokemaniac
    tbp Music_LookBeauty
    tbp Music_LookYoungster
ELSE
    tbp Music_Nothing
    tbp Music_PalletTown
    tbp Music_Pokecenter
    tbp Music_RBYGym
    tbp Music_Cities1
    tbp Music_Cities2
    tbp Music_CeladonCity
    tbp Music_CinnabarRemix
    tbp Music_VermilionCity
    tbp Music_Lavender
    tbp Music_SSAnne
    tbp Music_MeetProfOak
    tbp Music_MeetRival
    tbp Music_Shop
    tbp Music_Evolution
    tbp Music_PkmnHealed
    tbp Music_Routes1
    tbp Music_Routes2
    tbp Music_Routes3
    tbp Music_Route12
    tbp Music_RBYIndigoPlateau
    tbp Music_GymLeaderBattle
    tbp Music_TrainerBattle
    tbp Music_WildBattle
    tbp Music_FinalBattle
    tbp Music_TrainerVictory
    tbp Music_DefeatedWildMon
    tbp Music_GymLeaderVictory
    tbp Music_RBYTitleScreen
    tbp Music_RBYCredits
    tbp Music_RBYHallOfFame
    tbp Music_OaksLab
    tbp Music_BikeRiding
    tbp Music_Surfing
    tbp Music_RBYGameCorner
    tbp Music_IntroBattle
    tbp Music_Dungeon1
    tbp Music_Dungeon2
    tbp Music_Dungeon3
    tbp Music_CinnabarMansion
    tbp Music_PokemonTower
    tbp Music_SilphCo
    tbp Music_MeetEvilTrainer
    tbp Music_MeetFemaleTrainer
    tbp Music_MeetMaleTrainer
    tbp Music_RocketBattle
    tbp Music_ChampionBattle
    tbp Music_DarkCave
    tbp Music_BattleTowerTheme
    tbp Music_VictoryRoad
    tbp Music_CeruleanGSC
    tbp Music_ViridianCity
    tbp Music_TCG2GROverworld
    tbp Music_TCG2GameCorner
    tbp Music_FrontierBrain
    tbp Music_TCG2GRCastle
    tbp Music_TCG2GRDuelTheme2
    tbp Music_JigglypuffSong
    tbp Music_MuseumGuy
    tbp Music_TCGClub2
    tbp Music_JohtoTrainerBattle
    tbp Music_LookPokemaniac
    tbp Music_LookBeauty
    tbp Music_LookYoungster
ENDC