BTTrainerClassList:
; structure:  
; common - has 2 entries each in order to make the entire list exactly 32
	db YOUNGSTER, SPRITE_BUG_CATCHER, 3
	db YOUNGSTER, SPRITE_BUG_CATCHER, 7
	db JR__TRAINER_M, SPRITE_BLACK_HAIR_BOY_1, 1
	db JR__TRAINER_M, SPRITE_BLACK_HAIR_BOY_1, 0
	db JR__TRAINER_F, SPRITE_LASS, 1
	db JR__TRAINER_F, SPRITE_LASS, 0
	db COOLTRAINER_M, SPRITE_BLACK_HAIR_BOY_1, 8
	db COOLTRAINER_M, SPRITE_BLACK_HAIR_BOY_1, 5
	db COOLTRAINER_F, SPRITE_LASS, 8
	db COOLTRAINER_F, SPRITE_LASS, 5
; uncommon
	db BUG_CATCHER, SPRITE_BUG_CATCHER, 1
	db LASS, SPRITE_LASS, 2
	db HIKER, SPRITE_HIKER, 1
	db SAILOR, SPRITE_SAILOR, 7
	db POKEMANIAC, SPRITE_BLACK_HAIR_BOY_2, 6
	db SUPER_NERD, SPRITE_BLACK_HAIR_BOY_2, 4
	db BURGLAR, SPRITE_BLACK_HAIR_BOY_2, 0
	db ENGINEER, SPRITE_BLACK_HAIR_BOY_2, 9
	db FISHER, SPRITE_FISHER, 0
	db CUE_BALL, SPRITE_HIKER, 7
	db GAMBLER, SPRITE_GAMBLER, 2
	db BEAUTY, SPRITE_FOULARD_WOMAN, 2
	db PSYCHIC_TR, SPRITE_BUG_CATCHER, 9
	db ROCKER, SPRITE_ROCKER, 9
	db JUGGLER, SPRITE_ROCKER, 4
	db TAMER, SPRITE_ROCKER, 4
	db BIRD_KEEPER, SPRITE_BLACK_HAIR_BOY_1, 3
	db BLACKBELT, SPRITE_HIKER, 7
	db SCIENTIST, SPRITE_OAK_AIDE, 9
	db ROCKET, SPRITE_ROCKET, 8
	db GENTLEMAN, SPRITE_GENTLEMAN, 7
	db CHANNELER, SPRITE_MEDIUM, 8
	
BTMonList:
; List of 'mons, grouped in 8 roughly by types
; New set to accomodate new types and Pokemon
; Fire + Water set
	db CHARIZARD
	db KINGDRA
	db VAPOREON
	db MAGMORTAR
	db TENTACRUEL
	db CHANDELURE
	db GYARADOS
	db ARCANINE
; Bug + Rock set
	db SCIZOR
	db TYRANTRUM
	db HERACROSS
	db AERODACTYL
	db GALVANTULA
	db GIGALITH
	db MAGMORTAR
	db GYARADOS
; Grass+Ice set
	db VENUSAUR
	db MAMOSWINE
	db BRELOOM
	db CLOYSTER
	db EXEGGUTOR
	db LAPRAS
	db TROPIUS
	db CRYOGONAL
; Ground+Flying set
	db MAROWAK
	db SIGILYPH
	db GOLURK
	db PIDGEOT
	db EXCADRILL
	db CROBAT
	db DONPHAN
	db CHARIZARD
; Steel+Poison set
	db SCIZOR
	db VENUSAUR
	db SKARMORY
	db DRAPION
	db MAGNEZONE
	db TOXICROAK
	db STEELIX
	db NIDOKING
; Dragon+Fairy set
	db KINGDRA
	db CLEFABLE
	db HYDREIGON
	db SYLVEON
	db DRUDDIGON
	db FLORGES
	db FLYGON
	db MR_MIME
; Normal+Fighting set
	db PIDGEOT
	db HERACROSS
	db PERSIAN
	db BRELOOM
	db DODRIO
	db TOXICROAK
	db PORYGONZ
	db PRIMEAPE
; Ghost+Dark set
	db GENGAR
	db UMBREON
	db BANETTE
	db DRAPION
	db GOLURK
	db HYDREIGON
	db SPIRITOMB
	db PANGORO
; Electric+Psychic
	db MAGNEZONE
	db ALAKAZAM
	db MALAMAR
	db ELECTIVIRE
	db SLOWKING
	db RAICHU
	db EXEGGUTOR
	db AMPHAROS
